workflows:
  ios-testflight-build:
    name: iOS TestFlight Build
    environment:
      vars:
        APP_STORE_APP_ID: 6752107383
        BUNDLE_ID: "com.surveilone.ngmar"
        TEAM_ID: 2JQD483STZ
      flutter: stable
      xcode: 16.4
      cocoapods: default
      groups:
        - app_store_credentials   # contains issuer_id, key_id, private_key

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS app (manual signing via Codemagic UI profiles)
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY   # the contents of your .p8 file
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
