workflows:
  ios-testflight-build:
    name: iOS TestFlight Build
    environment:
      vars:
        APP_STORE_APP_ID: 6752107383
        BUNDLE_ID: "com.surveilone.ngmar"
        TEAM_ID: 2JQD483STZ
      flutter: stable
      xcode: 16.4
      cocoapods: default
      groups:
        - app_store_credentials   # contains APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS app (with Codemagic-managed signing)
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.log

    publishing:
      app_store_connect:
        apple_id: $APP_STORE_CONNECT_APPLE_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
