name: surveilone_ai_agent
description: SurveilOne AI Agent mobile application.
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.6
  graphql_flutter: ^5.1.2
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/products/IND_SUR/
    - assets/images/products/OUT_SUR/
    - assets/images/products/PHA_GOV/
    - assets/images/products/TIM_TRA/
    - assets/images/indoor.png
    - assets/images/outdoor.png
    - assets/images/phar.png
    - assets/images/timetrack.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
